language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "bTuStmaiUJTaN6+R1e7+ZP9b8gDXomk7TCaJlsk9LtOVzWritFttllmY3BLkEGCnISe/Z+DaXnjTmP94OqKNsSuLKYBy8qb77M6QaILgWkzF0tU7IfJ/EybQMIuHfQ0Zcm2/vs98rmoTI3ie9tP13s/jqzPVmLxVmtdkBYAZefj0PZlE8HnL59F+ZGzaNbWqIv/GV1iMzAKmKM9lB8UmtUs954Dq9xXizQo//64eByzuEFO9LmYa+VR3Dje5o1WWy+fT6mIx0KYNQRQdn3bbGz734fyhO7uCJx6hRqn+HAdZ/cb1pWE3iCQ4/efF8JK9l19vfCe8F+tQIZwrKreafK2U+pdnL9aPJxU64bqvE7ghBzFcAAZ9TTHkCuE+uIc8XSJ3WjkVWTAFJJK54T9YfWPpziM479U5wfvd5j9C5p1rTcc5EDqmn8A5wBtLQ7RqDzSMp/SU3+RFybkUo3ruf6/ele/GtK4x5op8sx7I3WeFL4ITkqqGJc48AJIV60x6QKJ1a8QTbWnOTK+TQ0yVQwBCVRGQZuytzC7NxFFuUt2ocuSMbRK4nLTNRVLaNVZhatPaXX1F0+3hqMaHYIupuTf+PEUhKr/zzB74oTjfCA38Q6nfUSGc4JUrR2UOWhntx7tco45l9Rc3VFmKUJxxtKPyNwHkDo5kp53HTyg3/qI="
  api_key: # a229
    secure: "Na9fsTK6UXvxi1GSftf037gV58GSmjQOWw7zh/r9MLgTbBSohwNsvm5YvT7vkcDC+5hCJXSBy1XTfSFr0gfILvgi8ZcUfhvKyn5Eqqf7HV2IlNgpi/2s4HDaElsj+aHs5DD0Jr/7crYfCzWkyHPD8dvLYcNnDMv0AdBja5G7OH7y8fNBk3fFVkdGv8nTVlKP3x3Zk7Mq1VQYgHSMR4NhsN2SV/xq3mSfNi3jZf0NSJYyucfaOdHxp3HhG9zahzm38/TMrlAmZtoo+Waoy06rgww0ZEjj6UQfHegaO/GdFlH284W+KrQXpkPBvyqzbx3Oxz3f0k8GtcaxbscoQz+Eul/NQ8RKDWQas5QTiF5c2zPYc1OgCvrZT/OyW/euLU1DWVVtUvjP5BauQAncewu8haBU2Fv3Uj2MVNuKb8grCBvhyDse8R5dbp0uuwX9D9xF5ouO2jHzu/ek61xy+z3ilN/o6h/ItqJPAr73GfrnlO2cS4VCQ081NslQQB2psckANrQE6+iiSfnF3PJc+WDDzGXkks35NILplfPMKxycN6c1d7tSKwfnY/VWaLFFDBv5Kh58WZsaR/KSyRlGG7QRL8u1hLAfL4neSdQDPzpl2KqZDNkg5PjQZJuKEGnfPwlR9m0uRIRUldEx/vw/iCBT/IbK4b3561R8Hq1ZFJrTpmY="
  on:
    tags: true
    node: lts/*
